import type { Metadata } from "next";
import { Cormorant } from "next/font/google";
import "@/assets/global.css";

const cormorant = Cormorant({
	weight: ["400", "500", "600"],
	subsets: ["latin", "cyrillic"]
});

export const metadata: Metadata = {
	title: "Amare",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body
			className={`${cormorant.className} antialiased`}
		>
		{children}
		</body>
		</html>
	);
}
